name: .NET Release on tag push

on:
  push:
    tags:
      - "V[0-9]*.[0-9]*.[0-9]*"
      - "V[0-9]*.[0-9]*.[0-9]*.[0-9]*"
      - "V[0-9]*.[0-9]*.[0-9]*-*"
      - "V[0-9]*.[0-9]*.[0-9]*.[0-9]*-*"

jobs:
  publish_and_release:

    runs-on: windows-latest
    permissions: 
      contents: write

    steps:
# ---- Checkout main source code
      - name: Checkout
        uses: actions/checkout@v6

# ---- CSPROJ Version preparations

      - name: Get csproj version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ./twilight-helper/TwilightHelper/TwilightHelper.csproj


# ---- .NET Preparations

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Restore dependencies
        run: dotnet restore ./twilight-helper/TwilightHelper/TwilightHelper.csproj
      
# ---- Publish and archive - net45
      - name: Publish net45 (AnyCPU)
        run: dotnet publish ./twilight-helper/TwilightHelper/TwilightHelper.csproj --configuration Release --framework net45 --output ./publish/net45/TwilightHelper
      - name: Archive published net45 (AnyCPU)
        run: Compress-Archive -Path "./publish/net45/*" -DestinationPath "./publish/TwilightHelper_V${{steps.get-version.outputs.version}}_net45.zip"
          
# ---- Publish and archive - net462
      - name: Publish net462 (AnyCPU)
        run: dotnet publish ./twilight-helper/TwilightHelper/TwilightHelper.csproj --configuration Release --framework net462 --output ./publish/net462/TwilightHelper
      - name: Archive published net462 (AnyCPU)
        run: Compress-Archive -Path "./publish/net462/*" -DestinationPath "./publish/TwilightHelper_V${{steps.get-version.outputs.version}}_net462.zip"
      
# ---- Publish and archive - net472
      - name: Publish net472 (AnyCPU)
        run: dotnet publish ./twilight-helper/TwilightHelper/TwilightHelper.csproj --configuration Release --framework net472 --output ./publish/net472/TwilightHelper
      - name: Archive published net472 (AnyCPU)
        run: Compress-Archive -Path "./publish/net472/*" -DestinationPath "./publish/TwilightHelper_V${{steps.get-version.outputs.version}}_net472.zip"
      
# ---- Publish and archive - net48
      - name: Publish net48 (AnyCPU)
        run: dotnet publish ./twilight-helper/TwilightHelper/TwilightHelper.csproj --configuration Release --framework net48 --output ./publish/net48/TwilightHelper
      - name: Archive published net48 (AnyCPU)
        run: Compress-Archive -Path "./publish/net48/*" -DestinationPath "./publish/TwilightHelper_V${{steps.get-version.outputs.version}}_net48.zip"
      
# ---- Publish and archive - net481
      - name: Publish net481 (AnyCPU)
        run: dotnet publish ./twilight-helper/TwilightHelper/TwilightHelper.csproj --configuration Release --framework net481 --output ./publish/net481/TwilightHelper
      - name: Archive published net481 (AnyCPU)
        run: Compress-Archive -Path "./publish/net481/*" -DestinationPath "./publish/TwilightHelper_V${{steps.get-version.outputs.version}}_net481.zip"

# ---- Creating github Release

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = "${{steps.get-version.outputs.version}}"
          $notesFile = "release_notes.md"
          
          # Check if the file exists, otherwise fallback to a default message
          if (Test-Path $notesFile) {
              gh release create ${{ github.ref_name }} `
                --title "${{ github.ref_name }}" `
                --notes-file $notesFile `
                ./publish/*.zip
          } else {
              gh release create ${{ github.ref_name }} `
                --title "${{ github.ref_name }}" `
                --notes "Automatic release for version V$version" `
                ./publish/*.zip
          }
